-- CREATE DATABASE
CREATE DATABASE hospital_management;
USE hospital_management;

-- CREATE TABLES
-- 1) Departments Table
CREATE TABLE departments (
    department_id INT PRIMARY KEY AUTO_INCREMENT,
    department_name VARCHAR(100) NOT NULL
);

-- 2) Doctors Table
CREATE TABLE doctors (
    doctor_id INT PRIMARY KEY AUTO_INCREMENT,
    doctor_name VARCHAR(100),
    specialization VARCHAR(100),
    salary DECIMAL(10,2),
    department_id INT,
    FOREIGN KEY (department_id) REFERENCES departments(department_id)
)auto_increment = 101;

-- 3) Patients Table
CREATE TABLE patients (
    patient_id INT PRIMARY KEY AUTO_INCREMENT,
    patient_name VARCHAR(100),
    gender VARCHAR(10),
    date_of_birth DATE,
    phone VARCHAR(15)
)auto_increment = 201;

-- 4) Appointments Table
CREATE TABLE appointments (
    appointment_id INT PRIMARY KEY AUTO_INCREMENT,
    patient_id INT,
    doctor_id INT,
    appointment_date DATE,
    status VARCHAR(50),
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id)
)auto_increment = 301;

-- 5) Treatments Table
CREATE TABLE treatments (
    treatment_id INT PRIMARY KEY AUTO_INCREMENT,
    appointment_id INT,
    treatment_description TEXT,
    treatment_cost DECIMAL(10,2),
    FOREIGN KEY (appointment_id) REFERENCES appointments(appointment_id)
)auto_increment = 401;

-- 6) Billing Table
CREATE TABLE billing (
    bill_id INT PRIMARY KEY AUTO_INCREMENT,
    patient_id INT,
    total_amount DECIMAL(10,2),
    payment_status VARCHAR(50),
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id)
)auto_increment = 501;

-- INSERT SAMPLE DATA 
INSERT INTO departments (department_name) VALUES
('Cardiology'),
('Neurology'),
('Orthopedics'),
('Pediatrics'),
('Dermatology'),
('General Medicine');

INSERT INTO doctors (doctor_name, specialization, salary, department_id) VALUES
('Dr. Rao', 'Cardiologist', 120000, 1),
('Dr. Mehta', 'Neurologist', 110000, 2),
('Dr. Sharma', 'Orthopedic', 100000, 3),
('Dr. Reddy', 'Pediatrician', 95000, 4),
('Dr. Kapoor', 'Dermatologist', 90000, 5),
('Dr. Nair', 'General Physician', 85000, 6),
('Dr. Verma', 'Cardiologist', 125000, 1),
('Dr. Iqbal', 'Neurologist', 115000, 2);


INSERT INTO patients (patient_name, gender, date_of_birth, phone) VALUES
('Amit Kumar', 'Male', '1995-05-10', '9876543210'),
('Priya Singh', 'Female', '1998-08-15', '9123456780'),
('Rahul Verma', 'Male', '1988-03-22', '9001112233'),
('Sneha R', 'Female', '2001-11-10', '9887766554'),
('Kiran Das', 'Male', '1975-09-18', '9012345678'),
('Anjali Mehra', 'Female', '1992-07-30', '9871234560'),
('Rohan Shetty', 'Male', '1985-12-05', '9988776655');

INSERT INTO appointments (patient_id, doctor_id, appointment_date, status) VALUES
(201, 101, '2024-01-10', 'Completed'),
(202, 102, '2024-01-12', 'Completed'),
(203, 104, '2024-02-01', 'Completed'),
(204, 105, '2024-02-05', 'Cancelled'),
(205, 106, '2024-02-07', 'Completed'),
(206, 101, '2024-02-10', 'Scheduled'),
(207, 102, '2024-02-15', 'Completed');

INSERT INTO treatments (appointment_id, treatment_description, treatment_cost) VALUES
(301, 'Heart Checkup', 5000),
(302, 'Brain MRI Scan', 8000),
(303, 'Child Vaccination', 2000),
(304, 'Skin Allergy Treatment', 3500),
(305, 'General Health Checkup', 1500),
(306, 'Cardiac Stress Test', 6000),
(307, 'Neurological Consultation', 7000);

INSERT INTO billing (patient_id, total_amount, payment_status) VALUES
(201, 5000, 'Paid'),
(202, 8000, 'Pending'),
(203, 2000, 'Paid'),
(204, 3500, 'Pending'),
(205, 1500, 'Paid'),
(206, 6000, 'Pending'),
(207, 7000, 'Paid');

select * from departments;
select * from doctors;
select * from patients;
select * from appointments;
select * from treatments;
select * from billing;

-- QUERIES
-- 1)List All Appointments with Doctor & Patient Name
SELECT DISTINCT p.patient_name, d.doctor_name, a.appointment_date, a.status
FROM appointments a
LEFT JOIN patients p ON a.patient_id = p.patient_id
JOIN doctors d ON a.doctor_id = d.doctor_id;

-- 2)Total Revenue Generated
SELECT SUM(total_amount) AS total_revenue
FROM billing;

-- 3)Department-wise Doctor Count
SELECT d.department_name, COUNT(doc.doctor_id) AS total_doctors
FROM doctors doc
JOIN departments d ON doc.department_id = d.department_id
GROUP BY d.department_name;

-- 4)Doctors Earning Above Average Salary
SELECT doctor_name, salary
FROM doctors
WHERE salary > (SELECT AVG(salary) FROM doctors);

-- 5) Patients with Pending Payments
SELECT p.patient_name, b.total_amount
FROM billing b
JOIN patients p ON b.patient_id = p.patient_id
WHERE b.payment_status = 'Pending';

-- 6) Total Hospital Revenue (Only Paid Bills)
SELECT SUM(total_amount) AS total_revenue
FROM billing
WHERE payment_status = 'Paid';

-- 7) Revenue Generated by Each Department
SELECT dep.department_name,
       SUM(t.treatment_cost) AS department_revenue
FROM treatments t
JOIN appointments a ON t.appointment_id = a.appointment_id
JOIN doctors d ON a.doctor_id = d.doctor_id
JOIN departments dep ON d.department_id = dep.department_id
GROUP BY dep.department_name
ORDER BY department_revenue DESC;

-- 8) Most Visited Doctor
SELECT d.doctor_name,
       COUNT(a.appointment_id) AS total_appointments
FROM appointments a
JOIN doctors d ON a.doctor_id = d.doctor_id
GROUP BY d.doctor_name
ORDER BY total_appointments DESC
LIMIT 1;

-- 9) Top 3 Highest Paid Doctors
SELECT doctor_name, salary
FROM doctors
ORDER BY salary DESC
LIMIT 3;

-- 10)Number of Appointments Per Doctor
SELECT d.doctor_name,
       COUNT(a.appointment_id) AS total_appointments
FROM doctors d
LEFT JOIN appointments a ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_name;

-- 11) Monthly Appointment Count
SELECT MONTH(appointment_date) AS month,
       COUNT(*) AS total_appointments
FROM appointments
GROUP BY MONTH(appointment_date)
ORDER BY month;

-- 12) Highest Revenue Generating Treatment
SELECT treatment_description,
       SUM(treatment_cost) AS total_generated
FROM treatments
GROUP BY treatment_description
ORDER BY total_generated DESC
LIMIT 1;

-- 13) Patients Who Visited More Than Once
SELECT p.patient_name,
       COUNT(a.appointment_id) AS visit_count
FROM appointments a
JOIN patients p ON a.patient_id = p.patient_id
GROUP BY p.patient_name
HAVING COUNT(a.appointment_id) > 1;

-- 14) Create View for Completed Appointments
CREATE VIEW completed_appointments AS
SELECT p.patient_name, d.doctor_name, a.appointment_date
FROM appointments a
JOIN patients p ON a.patient_id = p.patient_id
JOIN doctors d ON a.doctor_id = d.doctor_id
WHERE a.status = 'Completed';